// קטלוג מוצרים לחנות הדרופשיפינג.
// בפועל אפשר להזרים את הרשימה הזו מ-API של ספק (AliExpress / CJ / Spocket)
// או ממסד נתונים. כאן היא סטטית לצורך הדגמה ופיתוח.

window.PRODUCTS = [
  {
    id: "led-strip",
    name: "רצועת LED חכמה RGB",
    price: 89.9,
    compareAt: 149.9,
    category: "בית חכם",
    rating: 4.8,
    reviews: 1243,
    badge: "רב מכר",
    emoji: "💡",
    color: "#7c3aed",
    desc: "5 מטר תאורת RGB עם שליטה מהאפליקציה, סנכרון למוזיקה ו-16 מיליון צבעים.",
  },
  {
    id: "posture-corrector",
    name: "מיישר יציבה מגנטי",
    price: 69.0,
    compareAt: 129.0,
    category: "בריאות",
    rating: 4.6,
    reviews: 872,
    badge: "חדש",
    emoji: "🧍",
    color: "#0ea5e9",
    desc: "תמיכה עדינה לגב ולכתפיים, נוח ללבישה יומיומית מתחת לבגדים.",
  },
  {
    id: "mini-projector",
    name: "מקרן מיני נייד HD",
    price: 249.0,
    compareAt: 399.0,
    category: "אלקטרוניקה",
    rating: 4.7,
    reviews: 2109,
    badge: "רב מכר",
    emoji: "📽️",
    color: "#f59e0b",
    desc: "הקרנה עד 120 אינץ', תואם לטלפון, נטפליקס וקונסולות. כולל רמקול מובנה.",
  },
  {
    id: "electric-brush",
    name: "מברשת ניקוי חשמלית",
    price: 79.9,
    compareAt: 139.9,
    category: "בית",
    rating: 4.5,
    reviews: 654,
    emoji: "🧽",
    color: "#10b981",
    desc: "3 ראשים מתחלפים, עמידה במים, מנקה מקלחת, כיור וכלים במאמץ מינימלי.",
  },
  {
    id: "smart-bottle",
    name: "בקבוק מים חכם עם תזכורות",
    price: 99.0,
    compareAt: 169.0,
    category: "בריאות",
    rating: 4.4,
    reviews: 431,
    badge: "חדש",
    emoji: "🍶",
    color: "#06b6d4",
    desc: "מזכיר לשתות עם תאורת LED, מד טמפרטורה ומעקב צריכה יומית.",
  },
  {
    id: "car-organizer",
    name: "מארגן מושב לרכב",
    price: 59.9,
    compareAt: 99.9,
    category: "רכב",
    rating: 4.6,
    reviews: 988,
    emoji: "🚗",
    color: "#ef4444",
    desc: "תאים מרובים לטלפון, בקבוקים ומטענים. התקנה בשניות ללא כלים.",
  },
  {
    id: "wireless-earbuds",
    name: "אוזניות אלחוטיות Pro",
    price: 159.0,
    compareAt: 299.0,
    category: "אלקטרוניקה",
    rating: 4.7,
    reviews: 3021,
    badge: "רב מכר",
    emoji: "🎧",
    color: "#6366f1",
    desc: "ביטול רעשים אקטיבי, עד 30 שעות סוללה עם הכיסוי, עמידות למים IPX5.",
  },
  {
    id: "pet-brush",
    name: "מברשת טיפוח לחיות מחמד",
    price: 49.9,
    compareAt: 89.9,
    category: "חיות מחמד",
    rating: 4.8,
    reviews: 1567,
    badge: "רב מכר",
    emoji: "🐾",
    color: "#f97316",
    desc: "מסירה פרווה מתה בלחיצת כפתור, עדינה לעור ומתאימה לכלבים וחתולים.",
  },
  {
    id: "kitchen-scale",
    name: "משקל מטבח דיגיטלי",
    price: 44.9,
    compareAt: 79.9,
    category: "בית",
    rating: 4.5,
    reviews: 720,
    emoji: "⚖️",
    color: "#84cc16",
    desc: "דיוק של גרם בודד, משטח זכוכית מחוסמת, כיבוי אוטומטי וצג LCD.",
  },
  {
    id: "phone-stabilizer",
    name: "מייצב גימבל לטלפון",
    price: 219.0,
    compareAt: 349.0,
    category: "אלקטרוניקה",
    rating: 4.6,
    reviews: 512,
    badge: "חדש",
    emoji: "🤳",
    color: "#ec4899",
    desc: "צילום יציב ב-3 צירים, מעקב פנים אוטומטי ומצבי מקצוענים לווידאו.",
  },
  {
    id: "yoga-mat",
    name: "מזרן יוגה פרימיום",
    price: 89.0,
    compareAt: 149.0,
    category: "ספורט",
    rating: 4.7,
    reviews: 640,
    emoji: "🧘",
    color: "#14b8a6",
    desc: "עובי 8 מ\"מ, חומר אקולוגי נטול החלקה, כולל רצועת נשיאה.",
  },
  {
    id: "night-lamp",
    name: "מנורת לילה ירח תלת מימד",
    price: 74.9,
    compareAt: 119.9,
    category: "בית",
    rating: 4.9,
    reviews: 1890,
    badge: "רב מכר",
    emoji: "🌙",
    color: "#8b5cf6",
    desc: "16 צבעים עם שלט, נטענת ב-USB, מתנה מושלמת לחדר ילדים ולעיצוב.",
  },
];
